config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :babbles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "babbles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/babble.rb
class Babble < ApplicationRecord
    belongs_to :user
    has_many_attached :attachments
    validates :babble, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :babbles, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babbles_controller.rb
class BabblesController < ApplicationController
  before_action :set_babble, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /babbles or /babbles.json
  def index
    @babbles = Babble.all.order("created_at DESC")
    @babble = Babble.new
  end

  # GET /babbles/1 or /babbles/1.json
  def show
  end

  # GET /babbles/new
  def new
    @babble = current_user.babbles.build
  end

  # GET /babbles/1/edit
  def edit
  end

  # POST /babbles or /babbles.json
  def create
    @babble = current_user.babbles.build(babble_params)

    respond_to do |format|
      if @babble.save
        format.html { redirect_to root_path, notice: "Babble was successfully created." }
        format.json { render :show, status: :created, location: @babble }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @babble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babbles/1 or /babbles/1.json
  def update
    respond_to do |format|
      if @babble.update(babble_params)
        format.html { redirect_to babble_url(@babble), notice: "Babble was successfully updated." }
        format.json { render :show, status: :ok, location: @babble }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @babble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babbles/1 or /babbles/1.json
  def destroy
    @babble.destroy

    respond_to do |format|
      format.html { redirect_to babbles_url, notice: "Babble was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_babble
      @babble = Babble.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def babble_params
      params.require(:babble).permit(:babble, attachments: [])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private 

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babbles_helper.rb
module BabblesHelper
end

app/views/babbles/_babble.html.erb
<div id="<%= dom_id babble %>">
  <p>
    <strong>Babble:</strong>
    <%= babble.babble %>
  </p>

</div>

app/views/babbles/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
        <article class="media box">
            <figure class="media-left">
                <p class="image is-64x64">
                    <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
                </p>
            </figure>

            <div class="media-content">
                <%= render 'babbles/form' %>
            </div>
        </article>
    <% end %>

    <% @babbles.each do |babble| %>
        <div class="box">
            <article class="media">
                <div class="media-left">
                    <firgure class="image is-64x64">
                        <%= gravatar_image_tag(babble.user.email, size: 64, alt: babble.user.name) %>
                    </figure>
                </div>

                <div class="media-content">
                    <div class="content">
                        <strong><%= babble.user.name %></strong><br>
                        <small>@<%= babble.user.username %></small><br>
                        <p><%= babble.babble %></p>

                        <% if babble.attachments.attached? %>
                            <% babble.attachments.each do |attach| %>
                                <%= image_tag attach %>
                            <% end %>
                        <% end %>
                    </div>

                    <% if user_signed_in? && current_user.email == babble.user.email %>
                        <nav class="level">
                            <div class="level-left is-mobile">
                                <%= link_to babble, class: "level-item" do %>
                                    <span class="icon">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                    </span>
                                <% end %>

                                <%= link_to edit_babble_path(babble), class: "level-item" do %>
                                    <span class="icon">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </span>
                                <% end %>

                                <%= link_to babble, method: :delete, data: { confirm: "You sure you want to delete this babble?" }  do %>
                                    <span class="icon">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </span>
                                <% end %>
                            </div>
                        </nav>
                    <% end %>
                </div>
            </article>
        </div>
    <% end %>
</div>

app/views/babbles/_form.html.erb
<%= simple_form_for(@babble) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :babble, label: "Babble about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "Let's babble..." %>

      <%= f.file_field :attachments, label: "Attachments", wrapper: false, label_html: { class: "label" }, multiple: true %>
    </div>
  </div>

  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/babbles/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Profile</p>

        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
                    </figure>
                </div>

                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong><%= current_user.name %></strong><br>
                            <small><%= current_user.username %></small>
                        </p>
                    </div>
                </div>
            </article>
        </div>

        <div class="panel-block">
            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Babbles</p>
                        <p class="title is-6"><%= current_user.babbles.count %></p>
                    </div>
                </div>

                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Following</p>
                        <p class="title is-6">123</p>
                    </div>
                </div>

                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Followers</p>
                        <p class="title is-6">321K</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/views/babbles/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Trends</p>

        <a class="panel-block">
            Trend 1
        </a>

        <a class="panel-block">
            Trend 2
        </a>

        <a class="panel-block">
            Trend 3
        </a>

        <a class="panel-block">
            Trend 4
        </a>

        <a class="panel-block">
            Trend 5
        </a>

        <a class="panel-block">
            Trend 6
        </a>

        <div class="colorToggleContainer">
            <button id="colorToggle" class="button is-primary colorToggle">
                Toggle theme
            </button>
        </div>
    </nav>
</div>

app/views/babbles/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to Follow</p>

        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>

                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>John Smith</strong>
                            <small>@johnsmith</small>
                        </p>
                    </div>
                </div>
            </article>
        </div>

        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>

                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>John Smith</strong>
                            <small>@johnsmith</small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </nav>
</div>

app/views/babbles/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Babble</h1>
				<%= render 'form', babble: @babble %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', babbles_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/babbles/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>

      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/babbles/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Babble</h1>
					<%= render 'form', babble: @babble %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', babbles_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/babbles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @babble %>

<div>
  <%= link_to "Edit this babble", edit_babble_path(@babble) %> |
  <%= link_to "Back to babbles", babbles_path %>

  <%= button_to "Destroy this babble", @babble, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ByteBabble</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= render '/shared/nav' %>

    <%= yield %>
  </body>

  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const colorToggleButton = document.getElementById("colorToggle");
      const body = document.body;

      colorToggleButton.addEventListener("click", function () {
        body.classList.toggle("alt-color");
      });
    });
  </script>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar is-primary">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">ByteBabble</h1>
    <% end %>

    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to root_path, class: "navbar-start" do %>
            <h3 class="title is-6 navbar-item">Home</h3>
        <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
            <% if user_signed_in? %>
                <p class="control">
                    <%= link_to "New Babble", new_babble_path, class: "button is-info is-inverted" %>
                </p>

                <p class="control">
                    <%= link_to current_user.name, edit_user_registration_path, class: "button is-primary" %>
                </p>

                <p>
                    <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "button is-primary" %>
                </p>
            <% else %>
                <p class="control">
                    <%= link_to "Log in", new_user_session_path, class: "button is-primary" %>
                </p>

                <p class="control">
                    <%= link_to "Sign Up", new_user_registration_path, class: "button is-primary" %>
                </p>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>